// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGyNYkzxqHCKYU09erHsh6MM2Cz3Lc7ow',
    appId: '1:1051308485523:web:e80a8ce789b5d2a0999666',
    messagingSenderId: '1051308485523',
    projectId: 'flutterpractice-96a51',
    authDomain: 'flutterpractice-96a51.firebaseapp.com',
    storageBucket: 'flutterpractice-96a51.appspot.com',
    measurementId: 'G-VX33ST1P11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7zpoVAl1OOkuVnGxcRjVOSWzVYozW8EI',
    appId: '1:1051308485523:android:d83af2b635ea3490999666',
    messagingSenderId: '1051308485523',
    projectId: 'flutterpractice-96a51',
    storageBucket: 'flutterpractice-96a51.appspot.com',
  );
}
